//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Advanced.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ADVANCED_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LOG                  129
#define IDD_ADVANCED_DIALOG_CN          130
#define IDD_DIALOG_CUSTOM_CT            131
#define IDC_COMBO_RESOLUTION            1001
#define IDC_BUTTON_SNAPSHOT             1002
#define IDC_RADIO_SNAPSHOT_RES          1003
#define IDC_RADIO_SNAPSHOT_RES2         1004
#define IDC_BUTTON_CUSTOM_RES_SNAPSHOT  1005
#define IDC_BUTTON_ROI_RESET            1006
#define IDC_RADIO5                      1007
#define IDC_RADIO6                      1008
#define IDC_RADIO7                      1009
#define IDC_RADIO8                      1010
#define IDC_RADIO9                      1011
#define IDC_RADIO10                     1012
#define IDC_BUTTON_SOFT_TRIG_ONCE       1013
#define IDC_STATIC_PREVIEW              1014
#define IDC_RADIO11                     1016
#define IDC_RADIO12                     1017
#define IDC_RADIO13                     1018
#define IDC_RADIO14                     1019
#define IDC_SLD_ANALOG_GAIN             1020
#define IDC_SLD_EXPTIME                 1021
#define IDC_SLD_AE_TARGET               1022
#define IDC_STC_GAINTEXT                1023
#define IDC_STC_EXPTEXT                 1024
#define IDC_STC_AETARGETTEXT            1025
#define IDC_CHK_ANTI_FLICK              1026
#define IDC_BTN_WB_ONCE                 1027
#define IDC_SLD_RGAIN                   1028
#define IDC_SLD_GGAIN                   1029
#define IDC_SLD_BGAIN                   1030
#define IDC_SLD_SATURATION              1031
#define IDC_STC_SATURATIONTEXT          1032
#define IDC_STC_RTEXT                   1033
#define IDC_STC_GTEXT                   1034
#define IDC_STC_BTEXT                   1035
#define IDC_STC_RGAIN                   1036
#define IDC_STC_GGAIN                   1037
#define IDC_STATIC_GAIN                 1038
#define IDC_STATIC_TIME                 1039
#define IDC_STC_BGAIN                   1040
#define IDC_STATIC_TARGET               1041
#define IDC_BTN_WB_WIN_SET              1042
#define IDC_SLD_GAMMA                   1043
#define IDC_SLD_CONTRAST                1044
#define IDC_STC_GAMMATEXT               1045
#define IDC_STC_CONTRASTTEXT            1046
#define IDC_CHK_HFIP                    1047
#define IDC_CHK_VFLIP                   1048
#define IDC_SLD_EDGE_ENHANCE            1049
#define IDC_STC_SHARPNESS               1050
#define IDC_EDT_TRIGGER_COUNT           1051
#define IDC_EDT_TRIGGER_DELAY           1052
#define IDC_BUTTON_SAVE_PARAM           1053
#define IDC_BUTTON_LOAD_PARAM_FROM_FILE 1054
#define IDC_BUTTON_LOAD_DEFAULT         1055
#define IDC_CHECK_SAVE_ON_SWITCH        1056
#define IDC_CHECK_SAVE_ON_EXIT          1057
#define IDC_STC_BGAIN2                  1058
#define IDC_STC_EXPTEXT2                1060
#define IDC_LIST_TRACE_LOG              1061
#define IDC_BUTTON_PAUSE                1062
#define IDC_BUTTON_CLEAN                1063
#define IDC_CHECK_IGNORE_OVERLAY_SNAPSHOT 1063
#define IDC_COMBO_CT                    1064
#define IDC_BUTTON_CUSTOM_CT            1065
#define IDC_BUTTON1                     1066
#define IDC_EDIT1                       1067
#define IDC_EDIT2                       1068
#define IDC_EDIT3                       1069
#define IDC_EDIT4                       1070
#define IDC_EDIT5                       1071
#define IDC_EDIT6                       1072
#define IDC_EDIT7                       1073
#define IDC_EDIT8                       1074
#define IDC_EDIT9                       1075
#define IDC_RADIO1                      1076
#define IDC_EDIT10                      1076
#define IDC_EDIT11                      1077
#define IDC_COMBO_FRAME_SPEED           1077
#define IDC_EDIT12                      1078
#define IDC_EDIT_GAINTEXT               1078
#define IDC_EDIT_EXPTEXT                1079
#define IDC_BUTTON_BROWSE               1080
#define IDC_AUTO_SNAP                   1081
#define IDC_EDIT_FILE_PATH              1082
#define IDC_EDIT_TIME                   1083
#define IDC_RADIO2                      1084
#define IDC_RDO_50HZ                    1085
#define IDC_RDO_60HZ                    1086
#define IDC_RADIO3                      1087
#define IDC_RADIO4                      1088
#define IDC_STC_GAINTEXT_MIN            1089
#define IDC_STC_EXPTEXT_MIN             1090
#define IDC_STC_GAINTEXT_MAX            1091
#define IDC_STC_EXPTEXT_MAX             1092
#define IDC_BUTTON_EDIT_LUT             1094
#define IDC_BUTTON_LUT_LOAD             1095
#define IDC_BUTTON_AE_WIN_SET           1160
#define IDC_CHECK_CROSS_OVERLAY         1162
#define IDC_EDIT_CROSS_X                1175
#define IDC_EDIT_CROSS_Y                1181
#define IDC_EDIT_CROSS_COLOR            1182
#define IDC_RADIO_EXPOSURE_AUTO         1192
#define IDC_RADIO_EXPOSURE_MANUAL       1193
#define IDC_CHECK_DIS_AE_WIN            1194
#define IDC_CHECK_DIS_WB_WIN            1195
#define IDC_RADIO_WB_MODE               1200
#define IDC_RADIO_WB_MANUAL             1201
#define IDC_CHECK_NOISE_REDUCE          1202
#define IDC_RADIO_LUT_MODE_GEN          1203
#define IDC_RADIO_LUT_MODE_PREV         1204
#define IDC_RADIO_LUT_MODE_UDEF         1205
#define IDC_COMBO_PRESET_LUT            1206
#define IDC_STATIC_1                    1207
#define IDC_STATIC_2                    1208
#define IDC_STATICS_WB_MODE             1211
#define IDC_STATICS_SAT                 1214
#define IDC_STATICS_SM                  1215

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
